import { SolverResult, VariableCount } from '../types';
import { getMintermFromCoord, getMapStructure } from './kmapSolver';

/**
 * Generate standalone TikZ code for rendering the Karnaugh Map with grouping loops
 * Works out-of-the-box in standard LaTeX / Overleaf without extra obscure packages!
 */
export function generateTikzCode(
  result: SolverResult,
  cellValues: Record<number, '0' | '1' | 'X'>
): string {
  const { variableCount, variables, selectedPrimeImplicants, form } = result;
  const struct = getMapStructure(variableCount, variables);

  const colors = ['blue!70!black', 'red!80!black', 'green!60!black', 'orange!90!black', 'purple!80!black', 'cyan!80!black'];

  let code = `% Karnaugh Map generated by K Maps Solver
% Compilation requires: \\usepackage{tikz} \\usetikzlibrary{calc,shapes.geometric}
\\begin{tikzpicture}[x=1.3cm, y=1.3cm, font=\\sffamily]

  % Title and function definition
  \\node[above right, font=\\bfseries\\normalsize] at (-0.5, ${struct.rows + 0.8}) {K-Map for $${result.latexEquation}$};

`;

  // Handle single map (2, 3, 4 vars)
  if (variableCount <= 4) {
    const rows = struct.rows;
    const cols = struct.cols;

    // Draw grid
    code += `  % Grid Lines
  \\draw[thick] (0, 0) grid (${cols}, ${rows});

  % Diagonal header slash for variables
  \\draw[thick] (0, ${rows}) -- (-0.8, ${rows + 0.8});
  \\node[above right, font=\\small\\bfseries] at (-0.4, ${rows + 0.3}) {${struct.colVars.join('')}};
  \\node[below left, font=\\small\\bfseries] at (-0.4, ${rows + 0.4}) {${struct.rowVars.join('')}};

  % Column Gray Code labels
`;
    struct.colCodes.forEach((codeStr, c) => {
      code += `  \\node[above, font=\\small] at (${c + 0.5}, ${rows}) {${codeStr}};\n`;
    });

    code += `\n  % Row Gray Code labels\n`;
    struct.rowCodes.forEach((codeStr, r) => {
      // row 0 is top row in k-map, which is y = rows - 1 - r in TikZ
      const y = rows - 1 - r + 0.5;
      code += `  \\node[left, font=\\small] at (0, ${y}) {${codeStr}};\n`;
    });

    code += `\n  % Cell contents (values and minterm indices)\n`;
    for (let r = 0; r < rows; r++) {
      for (let c = 0; c < cols; c++) {
        const m = getMintermFromCoord(r, c, 0, variableCount);
        const val = cellValues[m] ?? '0';
        const yCenter = rows - 1 - r + 0.5;
        const xCenter = c + 0.5;

        // Minterm tiny index in top-left or bottom-right
        code += `  \\node[font=\\tiny, text=gray!70] at (${c + 0.85}, ${rows - 1 - r + 0.2}) {${m}};\n`;
        // Value
        const valStyle = val === '1' ? 'font=\\bfseries\\large' : val === 'X' ? 'font=\\bfseries, text=purple!80' : 'text=gray!50';
        code += `  \\node[${valStyle}] at (${xCenter}, ${yCenter}) {${val}};\n`;
      }
    }

    // Grouping loops
    code += `\n  % Prime Implicant Grouping Loops\n`;
    selectedPrimeImplicants.forEach((pi, idx) => {
      const color = colors[idx % colors.length];
      const term = form === 'SOP' ? pi.latexTerm : pi.latexPosTerm;

      code += `  % Group: $${term}$ covering {${pi.minterms.join(', ')}}\n`;
      // For each cell in this implicant, we calculate bounds
      const minRow = Math.min(...pi.cells.map(c => c.row));
      const maxRow = Math.max(...pi.cells.map(c => c.row));
      const minCol = Math.min(...pi.cells.map(c => c.col));
      const maxCol = Math.max(...pi.cells.map(c => c.col));

      // Single cell -> circle 'O' as standard
      if (pi.cells.length === 1) {
        const c = pi.cells[0];
        const cx = c.col + 0.5;
        const cy = rows - 1 - c.row + 0.5;
        code += `  \\draw[${color}, thick, fill=${color}!15] (${cx}, ${cy}) circle (0.38);\n`;
        return;
      }

      const cellRows = Array.from(new Set(pi.cells.map(c => c.row))).sort((a, b) => a - b);
      const cellCols = Array.from(new Set(pi.cells.map(c => c.col))).sort((a, b) => a - b);

      const isTbWrap = rows === 4 && cellRows.length === 2 && cellRows[0] === 0 && cellRows[1] === 3;
      const isLrWrap = cols === 4 && cellCols.length === 2 && cellCols[0] === 0 && cellCols[1] === 3;

      // 4 Corners Wrap
      if (isTbWrap && isLrWrap && cellRows.length === 2 && cellCols.length === 2) {
        code += `  % 4-Corner open corner grouping\n`;
        code += `  \\draw[${color}, thick] (0.85, 4.0) -- (0.85, 3.4) arc (0:-90:0.25) -- (0.0, 3.15);\n`;
        code += `  \\draw[${color}, thick] (3.15, 4.0) -- (3.15, 3.4) arc (180:270:0.25) -- (4.0, 3.15);\n`;
        code += `  \\draw[${color}, thick] (0.0, 0.85) -- (0.6, 0.85) arc (90:0:0.25) -- (0.85, 0.0);\n`;
        code += `  \\draw[${color}, thick] (4.0, 0.85) -- (3.4, 0.85) arc (90:180:0.25) -- (3.15, 0.0);\n`;
        return;
      }

      // Left-Right Wrap (open brackets extending past left and right borders)
      if (isLrWrap) {
        const yTop = rows - 1 - minRow + 0.9;
        const yBottom = rows - 1 - maxRow + 0.1;
        code += `  % Left-Right wrap open brackets\n`;
        code += `  \\draw[${color}, thick, fill=${color}!12] (-0.15, ${yTop}) -- (0.9, ${yTop}) [rounded corners=6pt] -- (0.9, ${yBottom}) [sharp corners] -- (-0.15, ${yBottom});\n`;
        code += `  \\draw[${color}, thick, fill=${color}!12] (4.15, ${yTop}) -- (3.1, ${yTop}) [rounded corners=6pt] -- (3.1, ${yBottom}) [sharp corners] -- (4.15, ${yBottom});\n`;
        return;
      }

      // Top-Bottom Wrap (open brackets extending past top and bottom borders)
      if (isTbWrap) {
        const xLeft = minCol + 0.1;
        const xRight = maxCol + 0.9;
        code += `  % Top-Bottom wrap open brackets\n`;
        code += `  \\draw[${color}, thick, fill=${color}!12] (${xLeft}, 4.15) -- (${xLeft}, 3.1) [rounded corners=6pt] -- (${xRight}, 3.1) [sharp corners] -- (${xRight}, 4.15);\n`;
        code += `  \\draw[${color}, thick, fill=${color}!12] (${xLeft}, -0.15) -- (${xLeft}, 0.9) [rounded corners=6pt] -- (${xRight}, 0.9) [sharp corners] -- (${xRight}, -0.15);\n`;
        return;
      }

      // Standard contiguous rectangular group
      const x1 = minCol + 0.1;
      const y1 = rows - 1 - maxRow + 0.1;
      const x2 = maxCol + 0.9;
      const y2 = rows - 1 - minRow + 0.9;
      code += `  \\draw[${color}, thick, rounded corners=8pt, fill=${color}!12] (${x1}, ${y1}) rectangle (${x2}, ${y2});\n`;
    });

  } else if (variableCount === 5) {
    // 5-variable dual 4x4 maps
    code += `  % Dual 4x4 sub-maps for 5-variable K-Map (A=0 and A=1)\n`;
    code += `  \\node[above, font=\\bfseries] at (2, 4.4) {Sub-map $${variables[0]}=0$};\n`;
    code += `  \\draw[thick] (0, 0) grid (4, 4);\n`;
    code += `  \\node[above, font=\\bfseries] at (7.5, 4.4) {Sub-map $${variables[0]}=1$};\n`;
    code += `  \\draw[thick] (5.5, 0) grid (9.5, 4);\n`;

    // Fill cells
    for (let sub = 0; sub < 2; sub++) {
      const xOff = sub === 0 ? 0 : 5.5;
      for (let r = 0; r < 4; r++) {
        for (let c = 0; c < 4; c++) {
          const m = getMintermFromCoord(r, c, sub, 5);
          const val = cellValues[m] ?? '0';
          const yCenter = 3 - r + 0.5;
          const xCenter = xOff + c + 0.5;
          code += `  \\node[font=\\tiny, text=gray!60] at (${xOff + c + 0.85}, ${3 - r + 0.2}) {${m}};\n`;
          code += `  \\node[${val === '1' ? 'font=\\bfseries' : 'text=gray!50'}] at (${xCenter}, ${yCenter}) {${val}};\n`;
        }
      }
    }
  }

  code += `\\end{tikzpicture}\n`;
  return code;
}

/**
 * Generates official LaTeX package `karnaugh-map` markup
 */
export function generateKarnaughMapPackageLatex(
  result: SolverResult,
  cellValues: Record<number, '0' | '1' | 'X'>
): string {
  const { variableCount, variables, selectedPrimeImplicants } = result;

  if (variableCount > 4) {
    return `% For 5-6 variables, please use the TikZ Standalone tab above.\n` + generateTikzCode(result, cellValues);
  }

  let code = `% Requires: \\usepackage{karnaugh-map}\n`;
  code += `\\begin{karnaugh-map}[${structMapHeader(variableCount, variables)}]\n`;
  code += `  \\minterms{${result.minterms.join(',')}}\n`;
  if (result.dontCares.length > 0) {
    code += `  \\terms{${result.dontCares.join(',')}}{$X$}\n`;
  }
  code += `  \\maxterms{${result.maxterms.join(',')}}\n`;

  // Implicants
  code += `  % Minimal grouping loops\n`;
  selectedPrimeImplicants.forEach((pi, idx) => {
    code += `  % Group: ${pi.termString}\n`;
    if (pi.cells.length === 1) {
      code += `  \\put(${pi.cells[0].col},${pi.cells[0].row}){};\n`;
    }
  });

  code += `\\end{karnaugh-map}\n`;
  code += `\n% Simplified Equation:\n% $${result.latexEquation}$\n`;
  return code;
}

function structMapHeader(varCount: VariableCount, variables: string[]): string {
  if (varCount === 2) return `2][2][1][$${variables[1]}$][$${variables[0]}$]`;
  if (varCount === 3) return `4][2][1][$${variables[1]}$][$${variables[2]}$][$${variables[0]}$]`;
  return `4][4][1][$${variables[2]}$][$${variables[3]}$][$${variables[0]}$][$${variables[1]}$]`;
}

/**
 * Generate Verilog / VHDL / C Hardware Description
 */
export function generateHardwareCode(
  result: SolverResult
): { verilog: string; vhdl: string; cCode: string } {
  const { variables, selectedPrimeImplicants } = result;

  // Verilog
  const termsVerilog = selectedPrimeImplicants.map(pi => {
    const parts: string[] = [];
    for (let i = 0; i < pi.binaryPattern.length; i++) {
      const bit = pi.binaryPattern[i];
      const v = variables[i];
      if (bit === '1') parts.push(v);
      else if (bit === '0') parts.push(`~${v}`);
    }
    return parts.length > 0 ? `(${parts.join(' & ')})` : '1\'b1';
  });

  const verilog = `// Minimal Boolean Logic Module
// Generated by K Maps Solver
module logic_kmap (
    input wire ${variables.join(', ')},
    output wire F
);
    // Minimal SOP equation: ${result.minimalEquation}
    assign F = ${termsVerilog.join(' |\n               ') || '1\'b0'};
endmodule`;

  // VHDL
  const termsVhdl = selectedPrimeImplicants.map(pi => {
    const parts: string[] = [];
    for (let i = 0; i < pi.binaryPattern.length; i++) {
      const bit = pi.binaryPattern[i];
      const v = variables[i];
      if (bit === '1') parts.push(v);
      else if (bit === '0') parts.push(`(not ${v})`);
    }
    return parts.length > 0 ? `(${parts.join(' and ')})` : '\'1\'';
  });

  const vhdl = `-- Minimal Boolean Logic Entity in VHDL
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity logic_kmap is
    Port (
        ${variables.map(v => `${v} : in STD_LOGIC`).join(';\n        ')};
        F : out STD_LOGIC
    );
end logic_kmap;

architecture Behavioral of logic_kmap is
begin
    -- Minimal SOP: ${result.minimalEquation}
    F <= ${termsVhdl.join(' or\n         ') || '\'0\''};
end Behavioral;`;

  // C / C++ logic function
  const termsC = selectedPrimeImplicants.map(pi => {
    const parts: string[] = [];
    for (let i = 0; i < pi.binaryPattern.length; i++) {
      const bit = pi.binaryPattern[i];
      const v = variables[i];
      if (bit === '1') parts.push(v);
      else if (bit === '0') parts.push(`!${v}`);
    }
    return parts.length > 0 ? `(${parts.join(' && ')})` : '1';
  });

  const cCode = `// Boolean Evaluation Function
#include <stdbool.h>

bool evaluate_kmap(${variables.map(v => `bool ${v}`).join(', ')}) {
    // Equation: ${result.minimalEquation}
    return ${termsC.join(' ||\n           ') || 'false'};
}`;

  return { verilog, vhdl, cCode };
}
